#!/bin/sh
set -e
rm -rf libs
version=0.4.3-aar-3
file=android-libs-$version.aar
url="https://dl.bintray.com/measurement-kit/android/org/openobservatory/measurement_kit/android-libs/$version/$file"
wget $url $url.asc
gpg2 --verify $file.asc
rm $file.asc
install -d libs/
mv $file libs/
