package org.openobservatory.engine;

/** SessionConfig contains settings for creating a Session. */
class SessionConfig {
    protected oonimkall.SessionConfig config;

    /** SessionConfig() creates a new SessionConfig instance. */
    public SessionConfig() {
        config = new oonimkall.SessionConfig();
    }

    /** setAssetsDir is a mandatory setting specifying the directory in
     * which you want the OONI Probe engine to store the assets. */
    public void setAssetsDir(String v) {
        config.setAssetsDir(v);
    }

    /** setLogger is an optional setting specifying a logger where
     * to send log messages generated by OONI Probe's engine. */
    public void setLogger(Logger v) {
        config.setLogger(v);
    }

    /** setSoftwareName is a mandatory setting specifying the name of
     * the application that is using OONI Probe's engine. */
    public void setSoftwareName(String v) {
        config.setSoftwareName(v);
    }

    /** setSoftwareVersion is a mandatory setting specifying the version of
     * the application that is using OONI Probe's engine. */
    public void setSoftwareVersion(String v) {
        config.setSoftwareVersion(v);
    }

    /** setStateDir is a mandatory setting specifying the directory in
     * which you want the OONI Probe engine to store its state. */
    public void setStateDir(String v) {
        config.setStateDir(v);
    }

    /** setTempDir is a mandatory setting specifying the directory in which
     * you want the OONI Probe engine to store temporary files. */
    public void setTempDir(String v) {
        config.setTempDir(v);
    }

    /** setVerbose controls whether to emit debug messages. This setting only
     * has effect if you also specify a Logger using setLogger. */
    public void setVerbose(boolean v) {
        config.setVerbose(v);
    }
}
